name: Auto Increment Version

on:
 push:
    branches: [ master ]
    
 workflow_dispatch:


jobs:
  increment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Get current version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: 'config.json'
        prop_path: 'mergeVersion'

    - name: New Version
      id: newVersion
      run: echo "::set-output name=newVersionNumber::$((${{steps.version.outputs.prop}}+1))"
      
      
    - name: Get Branch Name
      uses: tj-actions/branch-names@v4.8
      id: branchName
     
    - name: Atualizar versao
      uses: jossef/action-set-json-field@v1
      with:
        file: config.json
        field: mergeVersion
        value: ${{ steps.newVersion.outputs.newVersionNumber }}
        
    - name: Commita as mudancas
      run: |
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git checkout -b "AutoIncrementar"
            git commit -m "Auto increment version" -a
            git push origin "AutoIncrementar"
            gh pr create --title "Auto Increment Version" --body "Incrementa automaticamente a versão do pacote"
      env:
           GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}          
           
           
    - name: Find Pull Request
      uses: juliangruber/find-pull-request-action@v1
      id: find-pull-request
      with:
        branch: AutoIncrementar
    - run: echo "Pull Request ${number} (${sha})"
      env:
        number: ${{ steps.find-pull-request.outputs.number }}
        sha: ${{ steps.find-pull-request.outputs.head-sha }}
        
        
    - name: Approve Pull Request
      uses: juliangruber/approve-pull-request-action@v1
      with:
        github-token: ${{ secrets.BRUNO_GH_TOKEN }}
        number: ${{ steps.find-pull-request.outputs.number }}
        
    - name: Merge Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ steps.find-pull-request.outputs.number }}
        method: merge
